# Exercise 1: From the given dataset print the first and last five rows

In [2]:
import pandas as pd

pd.set_option('display.width', 1500) # or a larger number depending on your screen
pd.set_option('display.max_columns', None) # 'None' means show all columns

In [18]:
df = pd.read_csv("Automobile_data.csv")
print(df.head())
print(df.tail())


   index      company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
0      0  alfa-romero  convertible        88.6   168.8        dohc             four         111               21  13495.0
1      1  alfa-romero  convertible        88.6   168.8        dohc             four         111               21  16500.0
2      2  alfa-romero    hatchback        94.5   171.2        ohcv              six         154               19  16500.0
3      3         audi        sedan        99.8   176.6         ohc             four         102               24  13950.0
4      4         audi        sedan        99.4   176.6         ohc             five         115               18  17450.0
    index     company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
56     81  volkswagen      sedan        97.3   171.7         ohc             four          85               27   7975.0
57     82  volkswagen      s


# Exercise 2: Clean the dataset and update the CSV file

Replace all column values which contain ?, n.a, or NaN.


In [37]:
df = pd.read_csv("Automobile_data.csv", na_values={
    "price" : ["?", "n.c"]
})
df.to_csv("Automobile_data.csv")
print(df.iloc[20:30, :])

    index company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
20     29   honda      sedan        96.5   169.1         ohc             four         100               25  10345.0
21     30   isuzu      sedan        94.3   170.7         ohc             four          78               24   6785.0
22     31   isuzu      sedan        94.5   155.9         ohc             four          70               38      NaN
23     32   isuzu      sedan        94.5   155.9         ohc             four          70               38      NaN
24     33  jaguar      sedan       113.0   199.6        dohc              six         176               15  32250.0
25     34  jaguar      sedan       113.0   199.6        dohc              six         176               15  35550.0
26     35  jaguar      sedan       102.0   191.7        ohcv           twelve         262               13  36000.0
27     36   mazda  hatchback        93.1   159.1         ohc            


# Exercise 3: Find the most expensive car company name

Print most expensive car’s company name and price.


In [35]:
df = df[["company", "price"]][df.price == df['price'].max()] 
df


company    price
35  mercedes-benz  45400.0


# Exercise 4: Print All Toyota Cars details


In [41]:
df = pd.read_csv("Automobile_data.csv")
df = df[df.company == 'toyota']
df

Unnamed: 0  index company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
48          48     66  toyota  hatchback        95.7   158.7         ohc             four          62               35   5348.0
49          49     67  toyota  hatchback        95.7   158.7         ohc             four          62               31   6338.0
50          50     68  toyota  hatchback        95.7   158.7         ohc             four          62               31   6488.0
51          51     69  toyota      wagon        95.7   169.7         ohc             four          62               31   6918.0
52          52     70  toyota      wagon        95.7   169.7         ohc             four          62               27   7898.0
53          53     71  toyota      wagon        95.7   169.7         ohc             four          62               27   8778.0
54          54     79  toyota      wagon       104.5   187.8        dohc              six         156               19  15750.0


# Exercise 5: Count total cars per company


In [44]:
df = pd.read_csv("Automobile_data.csv")
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64


# Exercise 6: Find each company’s Higesht price car


In [47]:
car

company    price
35  mercedes-benz  45400.0


# Exercise 7: Find the average mileage of each car making company


In [16]:
df = pd.read_csv("Automobile_data.csv")
car_manufacturers = df.groupby("company")
mileageDf = car_manufacturers['average-mileage'].mean().reset_index()
mileageDf

company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000


# Exercise 8: Sort all cars by Price column


In [18]:
df = pd.read_csv('Automobile_data.csv')
df.sort_values(by='price', ascending=False)

Unnamed: 0  index        company   body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
35          35     47  mercedes-benz      hardtop       112.0   199.2        ohcv            eight         184               14  45400.0
11          11     14            bmw        sedan       103.5   193.8         ohc              six         182               16  41315.0
34          34     46  mercedes-benz        sedan       120.9   208.1        ohcv            eight         184               14  40960.0
46          46     62        porsche  convertible        89.5   168.9        ohcf              six         207               17  37028.0
12          12     15            bmw        sedan       110.0   197.0         ohc              six         182               15  36880.0
..         ...    ...            ...          ...         ...     ...         ...              ...         ...              ...      ...
27          27     36          mazda    hatchback        93.1   159.1         ohc             four          68               30   5195.0
13          13     16      chevrolet    hatchback        88.4   141.1           l            three          48               47   5151.0
22          22     31          isuzu        sedan        94.5   155.9         ohc             four          70               38      NaN
23          23     32          isuzu        sedan        94.5   155.9         ohc             four          70               38      NaN
47          47     63        porsche    hatchback        98.4   175.7       dohcv            eight         288               17      NaN

[61 rows x 11 columns]


# Exercise 9: Concatenate two data frames using the following conditions

Create two data frames using the following two dictionaries.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}\
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [21]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

df1 = pd.DataFrame(GermanCars)
df2 = pd.DataFrame(japaneseCars)

pd.concat([df1, df2], keys=['Germany', 'Japan'])

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900


# Exercise 10: Merge two data frames using the following condition

Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}\
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [22]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

df1 = pd.DataFrame(Car_Price)
df2 = pd.DataFrame(car_Horsepower)

pd.merge(df1, df2)

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160